name: Security & Quality Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      - name: Install Security Tools
        run: pip install bandit safety trufflehog

      - name: Dependency Vulnerability Scan (Safety)
        run: safety check -r backend/requirements.txt

      - name: Static Security Scan (Bandit)
        run: bandit -r backend/app -x backend/app/tests --severity-level medium --confidence-level medium

      - name: Secret Leak Scan (TruffleHog)
        run: trufflehog filesystem --entropy=False .

      - name: Run Unit Tests
        run: pytest --maxfail=1 --disable-warnings
