name: Pull Request Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pr_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      - name: Linting
        run: |
          pip install black isort flake8
          black --check .
          isort --check-only .
          flake8 .

      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings

      - name: Verify Branch Naming
        run: |
          branch="${{ github.head_ref }}"
          if [[ ! "$branch" =~ ^(feature|fix|docs|sec)\/.+ ]]; then
              echo "❌ Invalid branch name format"
              exit 1
          fi
